### ISSUE TITLE
Add number of connections to overview

### ISSUE THREAD

**Issue by richardignacio** [rpiwalletui/qtum-ui#2]
Can we add the number of nodes the RPi is connected to?  So add the "connections" value from "getinfo"?  Something like the following screenshot:

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/20646240/33235653-c9a7f552-d1f9-11e7-8659-b676fa893840.png">

**Comment by richardignacio** [comment]
I put in a pull request for this.  Let me know if that could work!

**Comment by ATJohnson** [comment]
Nice, I did have this in there originally. Not sure why I removed it. 
I will merge your PR.
